{
  "openapi": "3.0.3",
  "info": {
    "title": "Appointments API",
    "description": "A simple appointments api",
    "version": "1.0.0",
    "contact": {
      "name": "Douglas Pinheiro Goulart",
      "email": "douglaspigoulart@gmail.com",
      "url": "https://douglasgoulart.com/"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "Local API server"
    }
  ],
  "paths": {
    "/patients": {
      "get": {
        "summary": "Get the list of all patients",
        "description": "List all registered patients",
        "tags": ["Patients"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Patient"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Register a new patient",
        "description": "Creates a new patient",
        "tags": ["Patients"],
        "parameters": [
          {
            "in": "body",
            "name": "name",
            "description": "Name of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "Douglas Pinheiro Goulart"
          },
          {
            "in": "body",
            "name": "email",
            "description": "The email of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "douglaspigoulart@gmail.com"
          },
          {
            "in": "body",
            "name": "phone",
            "description": "The phone number of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "+55 55 5555-5555"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiError"
                },
                "example": {
                  "error": "The provided email address is invalid."
                }
              }
            }
          },
          "201": {
            "description": "Patient created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Patient"
                }
              }
            }
          }
        }
      }
    },
    "/patients/{patientId}": {
      "delete": {
        "summary": "Deletes a patient",
        "description": "Removes a patient from the registry",
        "tags": ["Patients"],
        "parameters": [
          {
            "in": "query",
            "name": "patientId",
            "description": "ID of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2a6e249a-077b-4b38-b90d-7ecef99a090f"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiError"
                },
                "example": {
                  "error": "Patient not found."
                }
              }
            }
          },
          "200": {
            "description": "Patient deleted successfully"
          }
        }
      }
    },
    "/dentists": {
      "get": {
        "summary": "Get the list of all dentists",
        "description": "List all registered dentists",
        "tags": ["Dentists"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Dentist"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Register a new dentist",
        "description": "Creates a new dentist",
        "tags": ["Dentists"],
        "parameters": [
          {
            "in": "body",
            "name": "name",
            "description": "Name of the dentist",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "Douglas Pinheiro Goulart"
          },
          {
            "in": "body",
            "name": "email",
            "description": "The email of the dentist",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "douglaspigoulart@gmail.com"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiError"
                },
                "example": {
                  "error": "The provided email address is invalid."
                }
              }
            }
          },
          "201": {
            "description": "Dentist created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Dentist"
                }
              }
            }
          }
        }
      }
    },
    "/dentists/{dentistId}": {
      "delete": {
        "summary": "Deletes a dentist",
        "description": "Removes a dentist from the registry",
        "tags": ["Dentists"],
        "parameters": [
          {
            "in": "query",
            "name": "dentistId",
            "description": "ID of the dentist",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2a6e249a-077b-4b38-b90d-7ecef99a090f"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiError"
                },
                "example": {
                  "error": "Dentist not found."
                }
              }
            }
          },
          "200": {
            "description": "Dentist deleted successfully"
          }
        }
      }
    },
    "/appointments/dentist/{dentistId}": {
      "get": {
        "summary": "List appointments of a dentist",
        "description": "List all of the appointments of a specific dentist",
        "tags": ["Appointments", "Dentists"],
        "parameters": [
          {
            "in": "query",
            "name": "dentistId",
            "description": "ID of the dentist",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "3da84353-d340-4f72-9856-17e22e34a62f"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Appointment"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appointments/patient/{patientId}": {
      "get": {
        "summary": "List appointments of a patient",
        "description": "List all of the appointments of a specific patient",
        "tags": ["Appointments", "Patients"],
        "parameters": [
          {
            "in": "query",
            "name": "patientId",
            "description": "ID of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "3da84353-d340-4f72-9856-17e22e34a62f"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Appointment"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appointments": {
      "post": {
        "summary": "Schedule a new appointment",
        "description": "Schedules a new appointment with start and end date",
        "tags": ["Appointments", "Dentists", "Patients"],
        "parameters": [
          {
            "in": "body",
            "name": "patientId",
            "description": "ID of the patient",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2a6e249a-077b-4b38-b90d-7ecef99a090f"
          },
          {
            "in": "body",
            "name": "dentistId",
            "description": "ID of the dentist",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "62c676cf-3c71-447f-8145-b901fd299a01"
          },
          {
            "in": "body",
            "name": "startsAt",
            "description": "Start date of the appointment",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2024-03-17 16:00:00"
          },
          {
            "in": "body",
            "name": "endsAt",
            "description": "End date of the appointment",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2024-03-17 17:00:00"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiError"
                },
                "example": {
                  "error": "Another appointment overlaps this appointment dates."
                }
              }
            }
          },
          "200": {
            "description": "Appointment scheduled successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Appointment"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiError": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string"
          }
        }
      },
      "Patient": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          }
        },
        "example": {
          "id": "2a6e249a-077b-4b38-b90d-7ecef99a090f",
          "name": "Julio Márcio Campos",
          "email": "juliomarciocampos@acritica.com.br",
          "phone": "+55 38 98833-9465",
          "createdAt": "2022-12-22T19:06:41.145Z"
        }
      },
      "Dentist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          }
        },
        "example": {
          "id": "62c676cf-3c71-447f-8145-b901fd299a01",
          "name": "Osvaldo Leonardo da Mota",
          "email": "osvaldo.leonardo.damota@wredenborg.se",
          "createdAt": "2022-12-22T19:05:56.766Z"
        }
      },
      "Appointment": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "patientId": {
            "type": "string"
          },
          "dentistId": {
            "type": "string"
          },
          "startsAt": {
            "type": "string"
          },
          "endsAt": {
            "type": "string"
          },
          "canceledAt": {
            "type": "string",
            "nullable": true
          },
          "createdAt": {
            "type": "string"
          }
        },
        "example": {
          "id": "491514a4-a4d9-4c61-b365-481aa1703a3c",
          "patientId": "2a6e249a-077b-4b38-b90d-7ecef99a090f",
          "dentistId": "62c676cf-3c71-447f-8145-b901fd299a01",
          "startsAt": "2023-03-15T12:00:00.000Z",
          "endsAt": "2023-03-15T14:00:00.000Z",
          "canceledAt": null,
          "createdAt": "2022-12-28T17:35:49.493Z"
        }
      }
    }
  }
}
